global:
    scrape_interval: 5s
    evaluation_interval: 5s
scrape_configs:
#here we can give any name
       - job_name: 'medilab-app-monolith-docker-compose'
       #here give prometheus actuator path
         metrics_path: 'actuator/prometheus'
         static_configs: 
             - targets: ['localhost:8087'] 
    