apiVersion: v1
kind: Service
metadata: 
  name: medilab-boot-app-service
  labels:
    app: medilab-boot-app
spec:
   type: NodePort
   selector: 
     app: medilab-boot-app 
   ports: 
     - protocol : TCP
       port: 8087
       targetPort: 8087
       nodePort: 30005