server:
  port: '${MEDILAB_BOOT_APP_PORT:8087}'
spring:
  application:
    name: medilab-monolith-app 
  datasource:
    driver-class-name: '${MEDILAB_BOOT_APP_DB_DRIVER:com.mysql.cj.jdbc.Driver}' 
    username: '${MEDILAB_BOOT_APP_DB_USERNAME:root}'
    password: '${MEDILAB_BOOT_APP_DB_PASSWORD:root}'
    url: jdbc:${MEDILAB_BOOT_APP_DB_TYPE:mysql}://${MEDILAB_BOOT_APP_DB_CONTAINER_NAME:localhost}:${MEDILAB_BOOT_APP_DB_PORT:3306}/${MEDILAB_BOOT_APP_DB:medilab_monolith_preclinic}
  h2:
    console:
      enabled: false
      path: /h2Console
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: '${MEDILAB_BOOT_APP_DB_DIALECT:org.hibernate.dialect.MySQL5InnoDBDialect}'
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
management:  endpoints:    web:      exposure:        include:        - '*'