apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessMode: 
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /opt/mysql-pv
  